sonar.projectKey=vite_gourmand_back
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9001
sonar.token=sqp_17cbae8a823a897d082bab64555ca079436b3ff2

sonar.sources=app,routes,config

sonar.exclusions=vendor/**,storage/**,bootstrap/**,node_modules/**,public/**,resources/css/**

sonar.sourceEncoding=UTF-8
sonar.php.coverage.reportPaths=
